# 权限配置文件
# 此文件用于管理群聊和私聊的黑白名单设置，以及聊天相关功能
# 支持热重载，修改后会自动生效

# 群聊权限设置
group_list_type = "whitelist"  # 群聊列表类型：whitelist（白名单）或 blacklist（黑名单）
group_list = []                # 群聊ID列表
# 当 group_list_type 为 whitelist 时，只有列表中的群聊可以使用机器人
# 当 group_list_type 为 blacklist 时，列表中的群聊无法使用机器人
# 示例：group_list = [123456789, 987654321]

# 私聊权限设置  
private_list_type = "whitelist"  # 私聊列表类型：whitelist（白名单）或 blacklist（黑名单）
private_list = []                # 用户ID列表
# 当 private_list_type 为 whitelist 时，只有列表中的用户可以私聊机器人
# 当 private_list_type 为 blacklist 时，列表中的用户无法私聊机器人
# 示例：private_list = [123456789, 987654321]

# 全局禁止设置
ban_user_id = []     # 全局禁止用户ID列表，这些用户无法在任何地方使用机器人
ban_qq_bot = false   # 是否屏蔽QQ官方机器人消息

# 聊天功能设置
enable_poke = true              # 是否启用戳一戳功能
ignore_non_self_poke = false    # 是否无视不是针对自己的戳一戳
poke_debounce_seconds = 3       # 戳一戳防抖时间（秒），在指定时间内第二次针对机器人的戳一戳将被忽略

# 视频处理设置
enable_video_analysis = true    # 是否启用视频识别功能
max_video_size_mb = 100         # 视频文件最大大小限制（MB）
download_timeout = 60           # 视频下载超时时间（秒）
supported_formats = ["mp4", "avi", "mov", "mkv", "flv", "wmv", "webm"]  # 支持的视频格式