# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mmc_message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mmc_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mmc_message.proto\x12\x0bmmc_message\"\xf4\x01\n\x07Message\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12&\n\x04type\x18\x02 \x01(\x0e\x32\x18.mmc_message.MessageType\x12\x17\n\x0fsender_platform\x18\x03 \x01(\t\x12\x17\n\x0ftarget_platform\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x13\n\x0brequire_ack\x18\x07 \x01(\x08\x12+\n\x06status\x18\x08 \x01(\x0e\x32\x1b.mmc_message.ResponseStatus\x12\x15\n\rerror_message\x18\t \x01(\t*\xc5\x01\n\x0bMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x12\n\x0eNORMAL_MESSAGE\x10\x01\x12\x13\n\x0f\x43OMMAND_MESSAGE\x10\x02\x12\x12\n\x0eNOTICE_MESSAGE\x10\x03\x12\r\n\tHEARTBEAT\x10\x04\x12\x12\n\x0eSYSTEM_MESSAGE\x10\x05\x12\x14\n\x10\x41\x44\x41PTER_RESPONSE\x10\x06\x12\x13\n\x0f\x41\x44\x41PTER_COMMAND\x10\x07\x12\x0f\n\x0bMESSAGE_ACK\x10\x08\x12\r\n\tHANDSHAKE\x10\t*i\n\x0eResponseStatus\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x12\x0b\n\x07TIMEOUT\x10\x04\x12\x0f\n\x0bUNSUPPORTED\x10\x05\x32Q\n\x0eMessageService\x12?\n\rMessageStream\x12\x14.mmc_message.Message\x1a\x14.mmc_message.Message(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mmc_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=282
  _globals['_MESSAGETYPE']._serialized_end=479
  _globals['_RESPONSESTATUS']._serialized_start=481
  _globals['_RESPONSESTATUS']._serialized_end=586
  _globals['_MESSAGE']._serialized_start=35
  _globals['_MESSAGE']._serialized_end=279
  _globals['_MESSAGESERVICE']._serialized_start=588
  _globals['_MESSAGESERVICE']._serialized_end=669
# @@protoc_insertion_point(module_scope)
